# DATA SCIENCE & BUSINESS ANALYTICS PARA PROFESIONALES

## NOTEBOOK COMPLEMENTARIO - Pandas y Numpy

Toma el siguiente csv 'Spotify-2000.csv' y realiza las siguientes operaciones:

* Lee el archivo como un dataframe a través de pandas.
* Ordena el dataframe por la columna 'Popularity' y muestra el título, artista y año de las 10 canciones más populares
* Muestra la matriz de correlación entre las columnas BPM, Energy y Danceability
* ¿Cuántas canciones hay por cada año?, ordena el dataframe por la columna year y muestra el conteo de canciones
* Convierte en un array de Numpy la columna Popularity y, obtén el número de fila que contiene la canción menos popular, posteriormente, muestra la fila completa con la canción menos popular en el dataframe.

## 1

Lee el archivo como un dataframe a través de pandas.

In [1]:
import pandas as pd

df = pd.read_csv("Spotify-2000.csv")

In [2]:
df.head(6)

,Index,Title,Artist,Top Genre,Year,Beats Per Minute (BPM),Energy,Danceability,Loudness (dB),Liveness,Valence,Length (Duration),Acousticness,Speechiness,Popularity
0,1,Sunrise,Norah Jones,adult standards,2004,157,30,53,-14,11,68,201,94,3,71
1,2,Black Night,Deep Purple,album rock,2000,135,79,50,-11,17,81,207,17,7,39
2,3,Clint Eastwood,Gorillaz,alternative hip hop,2001,168,69,66,-9,7,52,341,2,17,69
3,4,The Pretender,Foo Fighters,alternative metal,2007,173,96,43,-4,3,37,269,0,4,76
4,5,Waitin' On A Sunny Day,Bruce Springsteen,classic rock,2002,106,82,58,-5,10,87,256,1,3,59
5,6,The Road Ahead (Miles Of The Unknown),City To City,alternative pop rock,2004,99,46,54,-9,14,14,247,0,2,45

## 2

Ordena el dataframe por la columna 'Popularity' y muestra el título, artista y año de las 10 canciones más populares

In [3]:
df[['Title', 'Artist', 'Year', 'Popularity']].sort_values(['Popularity'], ascending=False)

,Title,Artist,Year,Popularity
793,Dance Monkey,Tones and I,2019,100
787,Memories,Maroon 5,2019,98
786,bad guy,Billie Eilish,2019,95
1641,All I Want for Christmas Is You,Mariah Carey,1994,95
688,Believer,Imagine Dragons,2017,88
...,...,...,...,...
605,Het Dorp - Live,Wim Sonneveld,2015,15
411,Peter Gunn Theme,"Emerson, Lake & Palmer",2010,14
624,Three Days In A Row,Anouk,2015,13
773,Hou Vol Hou Vast,BLØF,2018,12
1793,Sacrifice,Anouk,1998,11

In [4]:
df[['Title', 'Artist', 'Year', 'Popularity']].sort_values(['Popularity'], ascending=False).head(10)

                                Title               Artist  Year  Popularity
793                      Dance Monkey          Tones and I  2019         100
787                          Memories             Maroon 5  2019          98
786                           bad guy        Billie Eilish  2019          95
1641  All I Want for Christmas Is You         Mariah Carey  1994          95
688                          Believer      Imagine Dragons  2017          88
726                           Shallow            Lady Gaga  2018          88
683                           Perfect           Ed Sheeran  2017          87
687                      Shape of You           Ed Sheeran  2017          87
745                        High Hopes  Panic! At The Disco  2018          87
529                         All of Me          John Legend  2013          86

## 3

Muestra la matriz de correlación entre las columnas BPM, Energy y Danceability

In [5]:
df.columns

Index(['Index', 'Title', 'Artist', 'Top Genre', 'Year',
       'Beats Per Minute (BPM)', 'Energy', 'Danceability', 'Loudness (dB)',
       'Liveness', 'Valence', 'Length (Duration)', 'Acousticness',
       'Speechiness', 'Popularity'],
      dtype='object')

In [6]:
df[['Beats Per Minute (BPM)', 'Energy', 'Danceability']].corr()

                        Beats Per Minute (BPM)    Energy  Danceability
Beats Per Minute (BPM)                1.000000  0.156644     -0.140602
Energy                                0.156644  1.000000      0.139616
Danceability                         -0.140602  0.139616      1.000000

## 4

¿Cuántas canciones hay por cada año?, agrupa el dataframe por la columna year y muestra el conteo de canciones

In [13]:
df.groupby(['Year']).count()['Index']

Year
1956     1
1958     5
1959     3
1960     1
1961     1
        ..
2015    42
2016    35
2017    45
2018    52
2019    21
Name: Index, Length: 63, dtype: int64

## 5

Convierte en un array de Numpy la columna Popularity y, obtén el número de fila que contiene la canción menos popular, posteriormente, muestra la fila completa con la canción menos popular en el dataframe.

In [8]:
import numpy as np

popularidad = np.array(df['Popularity'])

In [9]:
menos_popular = popularidad.argmin()

In [10]:
menos_popular

1793

In [11]:
df[menos_popular:menos_popular+1]

,Index,Title,Artist,Top Genre,Year,Beats Per Minute (BPM),Energy,Danceability,Loudness (dB),Liveness,Valence,Length (Duration),Acousticness,Speechiness,Popularity
1793,1794,Sacrifice,Anouk,dutch indie,1998,136,17,54,-13,9,24,238,74,5,11